name: Test Pipeline

on:
  push:
    branches:
      - main

jobs:
  - job: RunTests
    displayName: 'Run Tests'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - checkout: self

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Use the appropriate Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run PyTest
        run: |
          pytest
